### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fs3088** [kmvan/inn-ao-request#60]
1. 分类中先翻页
2. 而后点击标签过滤（主题设置中快速分类添加的）
3. 然后404，看了下url会附带原页数，标签的内容没有这么多页

所以要怎么做啊。~！貌似不是wp的问题

**Comment by kmvan** [comment]
确实，10.0 a10版本修复

________________________________
From: fs3088 ***@***.***>
Sent: Saturday, May 22, 2021 4:43:36 PM
To: kmvan/inn-ao-report ***@***.***>
Cc: Km.Van ***@***.***>; Assign ***@***.***>
Subject: [kmvan/inn-ao-report] [BUG] (#60)


  1.  分类中先翻页
  2.  而后点击标签过滤（主题设置中快速分类添加的）
  3.  然后404，看了下url会附带原页数，标签的内容没有这么多页

所以要怎么做啊。~！貌似不是wp的问题

―

**Comment by kmvan** [comment]
fix in 10.0.0-alpha-10
